### ISSUE TITLE
Binary classification for quality query selection?

### ISSUE THREAD

**Issue by zhanggang001** [happinesslz/SEED#2]
Dear authors,

I noticed the line ```tgt["labels"].fill_(0) for tgt in bin_targets``` in seed_head.py. Does this indicate that a binary classification is conducted for quality query selection?

Thank you in advance!

**Comment by happinesslz** [comment]
@zhanggang001 Great question! I carefully reviewed the code, and I believe the line tgt["labels"].fill_(0) for tgt in bin_targets should be removed. As for quality query selection, we adopt a multi-class classifier rather than a binary classifier. We'll fix this issue and rerun the experiment. I anticipate the results will improve once this bug is addressed. Thanks again!

**Comment by happinesslz** [comment]
@zhanggang001  Great question! I carefully check our code, and  find the line of ' tgt["labels"].fill_(0) for tgt in bin_targets' should be removed. As for quality query selection, we adopt a multi-class classifier rather than a binary classifier. We'll fix this issue and rerun the experiment. I anticipate the results will improve once this bug is addressed. Thanks again!

**Comment by happinesslz** [comment]
@zhanggang001 Hi, we re-run this experiment (6 epoch with 100% training data for the small model)  after solving this bug and find there brings about 0.2-0.3 mAPH/L2 improvement!

**Comment by zhanggang001** [comment]
> @zhanggang001 Hi, we re-run this experiment (6 epoch with 100% training data for the small model) after solving this bug and find there brings about 0.2-0.3 mAPH/L2 improvement!

Thanks for your dedicated effort!!
